### PR TITLE
* truncate projects URL to exclude specific (and currently missing) p…

### LINKED ISSUE #67: project board link is 404
# Summary

the **project board** link in README.md is 404

# Background

This links to project 1, which presumably has been deleted.

# Details

A PR is pending in which the URL is truncated to point to the top of the projects page, which should continue to work so long as we keep projects enabled for this repo.

# Outcome

Once merged, the link will lead to somewhere useful.

### PR DESCRIPTION
**Pull request by ritjoe**
…roject

Closes #67

### CODE REVIEW

**Comment by jwflory** [comment]
@ritjoe Thanks for catching this. Since you already opened this PR to close #67, could you update your commit to point to the new URL for the project board? The link broke because I moved the project board from a project-level board to an organization-level board.

The link is here:

`https://github.com/orgs/FOSSRIT/projects/1?fullscreen=true`

**Comment by ritjoe** [comment]
On Tue, Oct 02, 2018 at 02:33:49PM -0700, Justin W. Flory wrote:
> @ritjoe Thanks for catching this. Since you already opened this PR to close #67
> , could you update your commit to point to the new URL for the project board?
> The link broke because I moved the project board from a project-level board to
> an organization-level board.
> 
> The link is here:
> 
> https://github.com/orgs/FOSSRIT/projects/1?fullscreen=true


That is the link I removed.  

I removed it because it returns a 404 for me, even now.

**Comment by ritjoe** [comment]
On Wed, Oct 03, 2018 at 05:41:23AM -0700, Joe wrote:
> On Tue, Oct 02, 2018 at 02:33:49PM -0700, Justin W. Flory wrote:
> > @ritjoe Thanks for catching this. Since you already opened this PR to close #
> 67
> > , could you update your commit to point to the new URL for the project board?
> > The link broke because I moved the project board from a project-level board
> to
> > an organization-level board.
> >
> > The link is here:
> >
> > https://github.com/orgs/FOSSRIT/projects/1?fullscreen=true
> 
> 
> That is the link I removed.
> 
> I removed it because it returns a 404 for me, even now.
> 
> 
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

So, I try to practice a certain level of ... let's call it browser hygeine: Sites that require authentication I often try to log into only from private windows, or a Tor browser instance. I clear browser history often (less often than I used to, but like I say, I try). I try to moderate, by some combination of uBlock Origin or NoScript what Javascript gets loaded and executed by my browser on behalf of other parties. I often browse sites, especially FOSS sites generally available to the public without logging in at all. It's tedious, and leaky, but I do what I can, and it is often very informative, if not as protective as I'd hope.

It occurred to me that you were not seeing the 404 because of the extent to which, in essence, you live in GitHub and remain logged in.

So, I logged in, followed the link, and can see the board.

I guess the question is, do you intend for the board to be private like that? 

What are the affordance and restrictions of the current policy (eg, who can or can't see what, under what conditions)?

Do we have other options for providing access and would any of them be more appropriate?

How do we decide who sees what, there?

Are there things you put in that board with the expectation that access to the information is restricted, that you'd leave out if it were globally readable? 

If so, how do you make that determination? Are there other tools we should consider for holding that information?

**Comment by jwflory** [comment]
> I guess the question is, do you intend for the board to be private like that?

Nope! GitHub added a feature in March or April to make organization boards public to members outside of the organization, but the default is private. I forgot to adjust it. It is now changed.

I am able to view it in a private window now. Can you also confirm?

**Comment by jwflory** [comment]
> That is the link I removed.

To clarify, the difference between the two board URLs is shown below:

* **Currently in README**: `https://github.com/FOSSRIT/tasks/projects/1?fullscreen=true`
* **New board URL**: `https://github.com/orgs/FOSSRIT/projects/1?fullscreen=true`

**Pull request closed without merging**
